# Your Name or Company
title: Murat Demirci

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: "Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do."

# Add your social links
social:
  - platform: github
    url: https://github.com/muratdemirci
  - platform: instagram
    url: https://www.instagram.com/deusmur
  - platform: twitter
    url: https://twitter.com/deusmur
  - platform: linkedin
    url: recursiveself

# General settings
url: https://muratdemirci.github.io/dreadpiratemurat
baseurl: "/dreadpiratemurat" 

markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center



# Credits: http://brianmaierjr.github.com/uni