# Your Name or Company
title: Dread Pirate Murat
site_name: dreadpiratemurat.com

# Description of your website. This is used for social sharing.
description:  Most of my experimental works and expressions. Welcome to my portfolio!

# A brief blurb about yourself
content: "This is a world where nothing is solved. You know, someone once told me time is a flat circle. Everything we’ve ever done, or will do, we’re gonna do over and over and over again. And that little boy and that computer, they’re gonna be in that room again. And again. And again. Forever."

# Add your social links
social:
  - platform: github
    url: https://github.com/muratdemirci
  - platform: instagram
    url: https://www.instagram.com/deusmur
  - platform: twitter
    url: https://twitter.com/deusmur
  - platform: linkedin
    url: https://www.linkedin.com/in/recursiveself
  - platform: medium
    url: https://medium.com/@deusmur
  - platform: dev.to
    url: https://dev.to/muratdemirci
  - platform: goodreads
    url: https://www.goodreads.com/recursiveself
  - platform: imdb
    url: https://www.imdb.com/list/ls095567664/
  - platform: superpeer
    url: https://superpeer.com/muratdemirci
  - platform: kommunity
    url: https://kommunity.com/@deusmur
  - platform: youtube
    url: https://bit.ly/deusmur_yt_sub

# General settings
# url: https://muratdemirci.github.io
# baseurl: /dreadpiratemurat

markdown: kramdown
sharing_image: share.jpg
#google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center

# Credits: http://brianmaierjr.github.com/uni
